In [4]:
!pip install matplotlib

   ---------------------------------------- 0.0/7.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/7.8 MB 3.3 MB/s eta 0:00:03
   -------- ------------------------------- 1.6/7.8 MB 4.2 MB/s eta 0:00:02
   ------------ --------------------------- 2.4/7.8 MB 4.3 MB/s eta 0:00:02
   ----------------- ---------------------- 3.4/7.8 MB 4.4 MB/s eta 0:00:02
   --------------------- ------------------ 4.2/7.8 MB 4.5 MB/s eta 0:00:01
   ---------------------------- ----------- 5.5/7.8 MB 4.7 MB/s eta 0:00:01
   ---------------------------------- ----- 6.8/7.8 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------- 7.8/7.8 MB 4.9 MB/s eta 0:00:00
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ----------------------- ---------------- 1.3/2.2 MB 6.7 MB/s eta 0:00:01
   ------------------------------------- -- 2.1/2.2 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 4.8 MB/s eta 0:00:00


In [6]:
!pip install seaborn

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [8]:
pd.__version__

'2.2.0'

In [12]:
!wget "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv"

--2024-09-29 23:20:03--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8002::154, 2606:50c0:8001::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: 'laptops.csv.1'

     0K .......... .......... .......... .......... .......... 17% 2.53M 0s
    50K .......... .......... .......... .......... .......... 34% 2.73M 0s
   100K .......... .......... .......... .......... .......... 51% 3.79M 0s
   150K .......... .......... .......... .......... .......... 68% 3.33M 0s
   200K .......... .......... .......... .......... .......... 85% 5.43M 0s
   250K .......... .......... .......... .......... .         100% 6.35M=0.08s

2024-09-29 23:20:03 (3.56 MB/s) - 'laptops.csv.1' saved [298573/298573]



In [32]:
df = pd.read_csv("./laptops.csv")

In [33]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [34]:
len(df)

2160

In [35]:
df.Brand.nunique()

27

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


In [37]:
dell = df[df['Brand']=="Dell"]
dell.describe()

RAM      Storage     Screen  Final Price
count  84.000000    84.000000  84.000000    84.000000
mean   11.380952   395.142857  14.686905  1153.839881
std     4.583640   175.543846   1.023669   671.795071
min     4.000000   128.000000  13.000000   379.000000
25%     8.000000   256.000000  14.000000   699.000000
50%     8.000000   256.000000  14.500000  1003.000000
75%    16.000000   512.000000  15.600000  1313.810000
max    32.000000  1000.000000  17.000000  3936.000000

In [38]:
# find mode and median for the column "Screen"
screen_mode = df['Screen'].mode()
screen_median = df['Screen'].median()

In [39]:
print("Mode of Screen: ", screen_mode[0])
print("Median of Screen: ", screen_median)

Mode of Screen:  15.6
Median of Screen:  15.6


In [40]:
df['Screen'].fillna(screen_mode[0])

0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64

In [41]:
print(df['Screen'].median())

15.6


In [42]:
innjoo = df[df['Brand']=='Innjoo']i

In [45]:
innjoo.head()

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02

In [46]:
innjoo = innjoo[['RAM', 'Storage', 'Screen']]

In [47]:
innjoo

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [48]:
innjoo_matrix = innjoo.to_numpy()

In [49]:
innjoo_matrix

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [50]:
innjoo_transposed = innjoo_matrix.T

In [51]:
innjoo_transposed

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [55]:
XTX = np.matmul(innjoo_transposed, innjoo_matrix)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [56]:
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [57]:
y = [1100, 1300, 800, 900, 1000, 1100]

In [59]:
w = np.matmul(np.matmul(inv_XTX,innjoo_transposed),y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [60]:
result = np.sum(w)

In [61]:
result

91.2998806299555